cuda
2022-11-19 09:02:29,798 - root - INFO - Task Started
2022-11-19 09:02:29,798 - root - INFO - [1/1] Data Preparing - Start
2022-11-19 09:02:43,997 - data - INFO - Train Dataset Info
2022-11-19 09:02:43,997 - data - INFO -  * Num. Users    : 7442
2022-11-19 09:02:43,998 - data - INFO -  * Max. UserID   : 7441
2022-11-19 09:02:43,998 - data - INFO -  * Num. Items    : 9454
2022-11-19 09:02:43,998 - data - INFO -  * Num. Records  : 1980769
2022-11-19 09:02:43,999 - data - INFO - Test Dataset Info
2022-11-19 09:02:43,999 - data - INFO -  * Num. Users    : 744
2022-11-19 09:02:43,999 - data - INFO -  * Max. UserID   : 7439
2022-11-19 09:02:44,000 - data - INFO -  * Num. Items    : 444
2022-11-19 09:02:44,000 - data - INFO -  * Num. Records  : 744
2022-11-19 09:02:44,184 - data - INFO - Valid Dataset Info
2022-11-19 09:02:44,185 - data - INFO -  * Num. Users    : 7434
2022-11-19 09:02:44,185 - data - INFO -  * Max. UserID   : 7441
2022-11-19 09:02:44,186 - data - INFO -  * Num. Items    : 9454
2022-11-19 09:02:44,186 - data - INFO -  * Num. Records  : 495193
2022-11-19 09:02:44,474 - root - INFO - [1/1] Data Preparing - Done
2022-11-19 09:02:44,474 - root - INFO - [2/2] Model Building - Start
2022-11-19 09:02:44,484 - build - INFO - No load model
2022-11-19 09:02:44,486 - root - INFO - [2/2] Model Building - Done
2022-11-19 09:02:44,486 - root - INFO - [3/3] Model Training - Start
2022-11-19 09:02:44,486 - train - INFO - Training Started : n_epoch=500
2022-11-19 09:02:44,735 - train - INFO -  * In epoch 0001, loss=0.693, acc=0.500, AUC=0.500
2022-11-19 09:02:44,736 - train - INFO -  * In epoch 0001, loss=0.693, acc=0.500, AUC=0.500, Best AUC
Traceback (most recent call last):
  File "/opt/ml/input/code/lightgcn/train.py", line 63, in <module>
    main()
  File "/opt/ml/input/code/lightgcn/train.py", line 47, in main
    train(
  File "/opt/ml/input/code/lightgcn/lightgcn/models.py", line 86, in train
    scheduler.step()
NameError: name 'scheduler' is not defined